apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-argo-yaml
  namespace: argocd
spec:
  project: default
  source: 
    repoURL:  https://github.com/Liubzzz/argogolang.git
    targetRevision: main
    path: argo
  destination:
    server: https://kubernetes.default.svc
    namespace: argogolangyaml
  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      seflHeal: true
      prune: true
